name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: Rust ${{matrix.rust}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Add fmt and clippy
      run: rustup component add rustfmt clippy
    - name: Build
      run: cargo build --verbose
    - name: Check format
      run: cargo fmt -- --check
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Run tests
      run: cargo test --verbose
